// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXKmnw2-sm8kWiAaNyaU6aRrjUDC1K8FY',
    appId: '1:1047765402693:web:97f82718b6daed0df48f2c',
    messagingSenderId: '1047765402693',
    projectId: 'ootd-19cb6',
    authDomain: 'ootd-19cb6.firebaseapp.com',
    storageBucket: 'ootd-19cb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGy7mJmxgOpfSVEqPlWpW_AtBHIBb_9M',
    appId: '1:1047765402693:android:7c5f29e2c5593e55f48f2c',
    messagingSenderId: '1047765402693',
    projectId: 'ootd-19cb6',
    storageBucket: 'ootd-19cb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyq5Crj5DTKqCJcglHnlYYDeKMSWNu1nc',
    appId: '1:1047765402693:ios:f92262ba78fa2a85f48f2c',
    messagingSenderId: '1047765402693',
    projectId: 'ootd-19cb6',
    storageBucket: 'ootd-19cb6.appspot.com',
    iosClientId: '1047765402693-551eghp6alqjforq8eg5rthol8a98gdi.apps.googleusercontent.com',
    iosBundleId: 'projectOutfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyq5Crj5DTKqCJcglHnlYYDeKMSWNu1nc',
    appId: '1:1047765402693:ios:f81351350d404971f48f2c',
    messagingSenderId: '1047765402693',
    projectId: 'ootd-19cb6',
    storageBucket: 'ootd-19cb6.appspot.com',
    iosClientId: '1047765402693-s2lpc1d9on1p1t5lmm72c7hkk0p6civn.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
