name: CI
on: push
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: cd app && flutter pub get
    - run: cd app && flutter test
    - run: cd app && flutter build ios --release --no-codesign